"""add entries table

Revision ID: 5c54b826d8dd
Revises: 7015c1efe98e
Create Date: 2026-01-17 07:39:18.642279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c54b826d8dd'
down_revision = '7015c1efe98e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reward', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('mood', sa.Enum('Struggling', 'Bad', 'Okay', 'Good', 'Great', name='mood_enum'), nullable=True),
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('behavior_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], name=op.f('fk_entries_behavior_id_behaviors')),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], name=op.f('fk_entries_trigger_id_triggers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    # ### end Alembic commands ###
